### ISSUE TITLE
Create button that floats over Praat window that calls "Log 1" 

### ISSUE THREAD

**Issue by mishaschwartz** [mlml/fvr#1]
Right now the user has to click Query > Log 1 or F12
This is neither intuitive or quick

**Comment by mishaschwartz** [comment]
Also update the new alternate vowel to the plot panel after every click.  Currently only updates when the FVR window comes back into focus

**Comment by mishaschwartz** [comment]
Labeled as a bug as well because every time the window comes back into focus a new set of identical vowels are being added to the plot.  This is causing an error when selecting an alternate measurement later.

**Comment by mishaschwartz** [comment]
Fixed with latest commit

**Comment by msonderegger** [comment]
great!
