### ISSUE TITLE
Redraw plot panel only after the window has fully been resized

### ISSUE THREAD

**Issue by mishaschwartz** [mlml/fvr#6]
Right now it tries to resize as the user is dragging which means it's really laggy if there are a lot of vowels on the plot

**Comment by mishaschwartz** [comment]
After a bit of digging this might not actually be worth it to fix.  
I also ran a few time tests and with 80 000+ vowels on the plot, resizing only really takes between 1.6 and 2.1 seconds.  It seems a bit of a delay when processing 80 000+ vowels is acceptable. 

However....possible processes to speed it up:
- process PlaceVowels() in chunks that take less time than the refresh rate and after a size event run those chunks one at a time in an idle event handler
- do some threading magic (would make the app even more bulky though so maybe not)

**Comment by msonderegger** [comment]
sounds sensible
